pipeline:
    name: ws_hw_pipeline
    identifier: ws_hw_pipeline
    projectIdentifier: DevOps_Team
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: ws_github
                repoName: hw_pipeline
                build: <+input>
    stages:
        - stage:
              name: Build
              identifier: Build
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.danfstatestcluster
                          namespace: harness-delegate-ng-statest
                          automountServiceAccountToken: true
                          nodeSelector: {}
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: build
                                identifier: build
                                spec:
                                    connectorRef: account.harnessImage
                                    image: maven:3.5.2-jdk-8-alpine
                                    shell: Sh
                                    command: echo hello world
